development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: jefflin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: jefflin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: jefflin
  password:
